# Generated by Django 4.0.3 on 2022-04-18 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ikea', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='info',
            new_name='greeter',
        ),
        migrations.AddField(
            model_name='employee',
            name='backoffice',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='employee',
            name='count_kk',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='employee',
            name='customer_service',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='employee',
            name='eco',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='employee',
            name='frontline',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='employee',
            name='operative_responsible',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='employee',
            name='pins_responsible',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='employee',
            name='smalland_1',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='employee',
            name='smalland_2',
            field=models.BooleanField(default=False),
        ),
    ]
