# Generated by Django 4.0.4 on 2022-05-02 10:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ikea', '0002_rename_info_employee_greeter_employee_backoffice_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeWorktime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.CharField(max_length=100)),
                ('end_time', models.CharField(max_length=100)),
                ('employeeID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ikea.employee')),
            ],
        ),
    ]
