# Generated by Django 4.0.3 on 2022-05-05 11:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ikea', '0004_allschedules'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeRequestWorktime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.CharField(max_length=100)),
                ('end_time', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=200)),
                ('employeeID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ikea.employee')),
            ],
        ),
    ]
