# Generated by Django 4.0.4 on 2022-05-05 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ikea', '0004_allschedules'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeeworktime',
            name='date_schedule',
            field=models.DateField(null=True),
        ),
    ]
