# Generated by Django 4.0.3 on 2022-05-05 11:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ikea', '0005_employeerequestworktime'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='EmployeeRequestWorktime',
            new_name='EmployeeRequest',
        ),
    ]
