# Generated by Django 4.0.3 on 2022-05-06 08:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ikea', '0006_rename_employeerequestworktime_employeerequest'),
        ('ikea', '0008_alter_employeeworktime_date_schedule'),
    ]

    operations = [
    ]
