# Generated by Django 4.0.4 on 2022-05-12 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ikea', '0008_alter_employeeworktime_date_schedule'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allschedules',
            name='date',
            field=models.CharField(max_length=50),
        ),
    ]
