# Generated by Django 4.0.3 on 2022-05-16 14:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ikea', '0009_alter_allschedules_date'),
        ('ikea', '0010_employeerequest_date_schedule'),
    ]

    operations = [
    ]
